# Generated by Django 3.1.4 on 2021-02-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210226_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='corn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plusone',
            name='corn',
            field=models.BooleanField(default=True),
        ),
    ]
