# Generated by Django 3.1.4 on 2021-08-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='corn',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='foodchoice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plusone',
            name='corn',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='plusone',
            name='foodchoice',
            field=models.IntegerField(null=True),
        ),
    ]
